In [71]:
import numpy as np

In [107]:
def calculate_rowhash(input_rows, hash_function):
    return hash_function(input_rows)

def calculate_signaturematrix(input_data, hash_functions):
    # get the row hash values
    input_rows = np.array(range(0, input_data.shape[0]))
    row_hash = np.empty((len(hash_functions), input_rows.size))
    for i in range(len(hash_functions)):
        row_hash[i] = hash_functions[i](input_rows)

    # initialize the signature matrix
    signature_matrix = np.empty((len(hash_functions), input_data.shape[1]))
    signature_matrix.fill(np.inf)

    for row_index in range(input_data.shape[0]):
        for column_index in range(input_data.shape[1]):
            for hash_index in range(len(hash_functions)):
                if input_data[row_index][column_index] == 1:
                    signature_matrix[hash_index][column_index] = min(
                        signature_matrix[hash_index][column_index],
                        row_hash[hash_index][row_index])

        #print("-- stage", row_index, "---")
        #print(signature_matrix)

    return signature_matrix

# test the minhash function
data_matrix = np.array([
    [0, 1, 1, 0],
    [1, 1, 0, 0],
    [1, 0, 0, 0],
    [0, 0, 1, 0],
    [1, 1, 0, 1]
])

calculate_signaturematrix(data_matrix, [
    lambda x : (x + 1) % 5, 
    lambda x : (2 * x + 3) % 5
])

#print(data_rowhash)


array([[0., 0., 1., 0.],
       [0., 0., 3., 1.]])

## Question 1

In [108]:
data_matrix = np.array([
    [0, 1, 0, 1, 1],
    [0, 0, 1, 0, 0],
    [1, 1, 0, 0, 0],
    [1, 0, 1, 0, 1],
    [1, 0, 0, 0, 0],
    [0, 0, 1, 1, 0]
])

calculate_signaturematrix(data_matrix, [
    lambda x : (x + 5) % 6,
    lambda x : (5 * x + 3) % 6
])

array([[1., 1., 0., 4., 2.],
       [0., 1., 0., 3., 0.]])

## Question 2

In [110]:
data_matrix = np.array([
    [1, 1, 0, 0, 0],
    [0, 1, 1, 1, 0],
    [1, 0, 1, 0, 0],
    [0, 0, 0, 0, 1],
    [1, 0, 0, 1, 1],
    [0, 0, 1, 0, 0]
])

calculate_signaturematrix(data_matrix, [
    lambda x : (x + 1) % 6,
    lambda x : (2 * x + 3) % 6,
    lambda x : (5 * x + 3) % 6
])

array([[1., 1., 0., 2., 4.],
       [1., 3., 1., 5., 3.],
       [1., 2., 1., 2., 0.]])