# Activity 5: Applying the basic idea of PageRank

## Web References

- [Visualisation of graphs](https://igraph.org/python/doc/tutorial/visualisation.html#graph-layouts)
- [igraph goes to the very edge of the bounding box](https://stackoverflow.com/questions/14504268/igraph-goes-to-the-very-edge-of-the-bounding-box)

## Import Libraries

In [1]:
import pandas as pd
import numpy as np
import igraph as gp

## Data Load

In [2]:
grap_edges = [
    ['A', 'B'],
    ['A', 'C'],
    ['A', 'D'],
    ['B', 'D'],
    ['C', 'A'],
    ['C', 'D'],
    ['D', 'A'],
    ['D', 'C']
]

## PageRank Class

In [130]:
class PageRank:
    """
    Implement the PageRank algorithm using matrix manipulation.
    """
    def __init__(self, edges):
        """
        Create a dafault instance of the class.

        Args:
            edges: The edges to create the page graph from.
        """
        self.graph = self.createGraph(edges)

    def createGraph(self, edges):
        """
        Construct a graph from the page edges.

        Args:
            edges: The edges to create the page graph from.

        Returns:
            The graph created from the input edges.
        """
        return gp.Graph.TupleList(edges, directed=True)


    def plotGraph(self, width=300, height=300, margin=15, layout='auto', edge_curved=True):
        """
        Plot the page graph.
        """
        return gp.plot(self.graph, 
            vertex_label=self.graph.vs["name"], 
            layout=layout, 
            margin=margin, 
            bbox=(0, 0, width, height), 
            edge_curved=edge_curved)

    def get_transitionmatrix(self):
        """
        Get the transation matrix of the graph.

        Returns:
            A numpy array containing the transition matrix.
        """
        # get the adjacency matrix
        adjacent_matrix = np.array(self.graph.get_adjacency().data)

        # add the self loop
        self_loop = adjacent_matrix + np.identity(len(adjacent_matrix))

        # create the normalised transition matrix
        transition_matrix = np.divide(self_loop, self_loop.sum(axis=0))        

        return transition_matrix


"""test the pagerank class"""
# create the test edges
test_edges = [
    ['A', 'B'],
    ['A', 'C'],
    ['B', 'D'],
    ['C', 'A'],
    ['C', 'B'],
    ['C', 'D'],
    ['D', 'C']
]

pageRank = PageRank(test_edges)
pageRank.plotGraph(width=100, height=100, layout='grid', edge_curved=False)

print(pageRank.graph.get_adjlist(mode='out'))
print(pageRank.graph.get_adjlist(mode='in'))
print()
print(pageRank.get_transitionmatrix())

[[1, 2], [3], [0, 1, 3], [2]]
[[2], [0, 2], [0, 3], [1, 2]]

[[0.5        0.33333333 0.33333333 0.        ]
 [0.         0.33333333 0.         0.33333333]
 [0.5        0.33333333 0.33333333 0.33333333]
 [0.         0.         0.33333333 0.33333333]]
