In [3]:
import numpy as np

In [6]:
mg = np.array([
    [0, 1, 1, 0, 0, 0],
    [1, 0, 1, 0, 0, 0],
    [1, 1, 0, 1, 0, 0],
    [0, 0, 1, 0, 1, 1],
    [0, 0, 0, 1, 0, 1],
    [0, 0, 0, 1, 1, 0]])

In [13]:
mdg = mg + np.identity(6)
mdg

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [15]:
# mg^2
np.matmul(mdg, mdg)

array([[3., 3., 3., 1., 0., 0.],
       [3., 3., 3., 1., 0., 0.],
       [3., 3., 4., 2., 1., 1.],
       [1., 1., 2., 4., 3., 3.],
       [0., 0., 1., 3., 3., 3.],
       [0., 0., 1., 3., 3., 3.]])

In [23]:
# tgd
tgd =  np.divide(mdg, mdg.sum(axis=0))
print(tgd)

[[0.33333333 0.33333333 0.25       0.         0.         0.        ]
 [0.33333333 0.33333333 0.25       0.         0.         0.        ]
 [0.33333333 0.33333333 0.25       0.25       0.         0.        ]
 [0.         0.         0.25       0.25       0.33333333 0.33333333]
 [0.         0.         0.         0.25       0.33333333 0.33333333]
 [0.         0.         0.         0.25       0.33333333 0.33333333]]


In [25]:
a = tgd
for i in range(0, 55):
    a = np.matmul(a, tgd)

print(a)

[[0.15004492 0.15004492 0.1500261  0.1499739  0.14995508 0.14995508]
 [0.15004492 0.15004492 0.1500261  0.1499739  0.14995508 0.14995508]
 [0.2000348  0.2000348  0.20002023 0.19997977 0.1999652  0.1999652 ]
 [0.1999652  0.1999652  0.19997977 0.20002023 0.2000348  0.2000348 ]
 [0.14995508 0.14995508 0.1499739  0.1500261  0.15004492 0.15004492]
 [0.14995508 0.14995508 0.1499739  0.1500261  0.15004492 0.15004492]]


# Example Sample
https://learning.edx.org/course/course-v1:AdelaideX+BigDataX+1T2021/block-v1:AdelaideX+BigDataX+1T2021+type@sequential+block@92e874921909456699eeccdd520e4c53/block-v1:AdelaideX+BigDataX+1T2021+type@vertical+block@da9847c9aef245ba836046faca4a51c7

In [100]:
def mcl(adjacent_matrix, p, r, steps, prune=None): 
    # add the self loop
    self_loop = adjacent_matrix + np.identity(len(adjacent_matrix))
    
    # create the normalised transition matrix
    transition_matrix = np.divide(self_loop, self_loop.sum(axis=0))

    # multiply the normalised transition matrix by itself p times
    for step in range(0, steps):
        multiplied_matrix = transition_matrix
        for i in range(0, p):
            multiplied_matrix = np.matmul(multiplied_matrix, multiplied_matrix)

        # inflate resulting matrix with parameter r
        transition_matrix = np.power(multiplied_matrix, r)
        transition_matrix = np.divide(transition_matrix, transition_matrix.sum(axis=0))

        # prune values
        if prune is not None:
            transition_matrix[transition_matrix < prune] = 0

    return transition_matrix


matrix = np.array([
[0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0],
[1, 1, 1, 0, 0, 0],
[0, 0, 0, 1, 1, 1],
[0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0]])

print(mcl(matrix, 2, 2, 13))

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


## Question 21

In [101]:
matrix = np.array([
    [0, 1, 0],
    [1, 0, 1],
    [0, 1, 0]
])

print(mcl(matrix, p=2, r=2, steps=2, prune=0.1))

[[0.14267251 0.14260591 0.14253931]
 [0.71478817 0.71478819 0.71478817]
 [0.14253931 0.14260591 0.14267251]]


## Question 23

In [102]:
matrix = np.array([
    [0, 1, 0],
    [1, 0, 1],
    [0, 1, 0]
])

print(mcl(matrix, p=2, r=2, steps=3, prune=0.1))

[[0.         0.         0.        ]
 [0.92626313 0.92626313 0.92626313]
 [0.         0.         0.        ]]


## Question 25

In [104]:
matrix = np.array([
    [0, 1, 0],
    [1, 0, 1],
    [0, 1, 0]
])

print(mcl(matrix, p=3, r=3, steps=20, prune=0.1))

[[0. 0. 0.]
 [1. 1. 1.]
 [0. 0. 0.]]


## Question 26-27

In [105]:
matrix = np.array([
    [0, 1, 0],
    [1, 0, 1],
    [0, 1, 0]
])

print(mcl(matrix, p=3, r=3, steps=2, prune=0.1))

[[0.         0.         0.        ]
 [0.95054097 0.95054097 0.95054097]
 [0.         0.         0.        ]]


## Question 28

In [106]:
matrix = np.array([
    [0, 1, 0],
    [1, 0, 1],
    [0, 1, 0]
])

print(mcl(matrix, p=3, r=3, steps=3, prune=0.1))

[[0. 0. 0.]
 [1. 1. 1.]
 [0. 0. 0.]]
